--PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
	    id INTEGER PRIMARY KEY,
		title VARCHAR,
		text VARCHAR,
		community VARCHAR,
		url VARCHAR,
		username VARCHAR, 
		date VARCHAR,
		
		upvotes INTEGER,
		downvotes INTEGER,
		score INTEGER
		
		-- UNIQUE(title, community, username)
	);
INSERT INTO "posts" VALUES(0,'Quiquia dolor neque sed amet neque neque','Velit porro magnam voluptatem voluptatem labore. Quisquam dolorem consectetur adipisci est. Ut labore dolorem tempora modi. Velit adipisci ut quisquam quaerat ut porro. Amet voluptatem sed sit. Ipsum neque numquam neque non. Magnam neque adipisci voluptatem modi.','adipisci','http://www.sit.com','Dolor','100611',86,41,45);
INSERT INTO "posts" VALUES(1,'Dolor dolore eius consectetur','Modi adipisci voluptatem dolore labore adipisci. Ipsum eius modi labore. Magnam est quaerat consectetur quisquam. Quisquam porro magnam sit. Aliquam sed magnam ipsum sit voluptatem quaerat tempora.','modi','http://www.sit.com','Dolor','110502',18,0,18);
INSERT INTO "posts" VALUES(2,'Est voluptatem amet quisquam sed','Amet sed dolor modi ut ipsum magnam. Sit dolorem eius neque. Dolor quiquia aliquam porro numquam velit consectetur. Est quaerat quaerat magnam velit. Voluptatem sed modi dolor. Dolorem aliquam aliquam magnam est aliquam porro quiquia. Ipsum dolore sed amet numquam. Neque magnam modi tempora tempora. Neque quisquam adipisci aliquam.','dolore','http://www.consectetur.com','Non','001107',72,39,33);
INSERT INTO "posts" VALUES(3,'Modi numquam labore ipsum','Porro numquam numquam est etincidunt quiquia. Modi velit aliquam consectetur amet. Velit sit quiquia neque consectetur. Sit dolore consectetur tempora. Neque labore neque quaerat eius etincidunt dolor. Est neque magnam modi dolor. Velit sed labore tempora quiquia dolor. Etincidunt sit aliquam sed non quaerat.','modi','http://www.labore.com','Ut','080829',25,41,-16);
INSERT INTO "posts" VALUES(4,'Magnam quaerat eius ut aliquam dolore eius','Magnam quiquia velit tempora adipisci. Porro labore adipisci tempora dolorem magnam ut non. Neque velit numquam ut consectetur amet. Eius magnam etincidunt voluptatem quaerat. Aliquam sed adipisci etincidunt dolore sed quiquia. Magnam est numquam etincidunt porro neque quaerat magnam. Modi tempora porro quisquam non voluptatem labore. Est porro dolor dolor porro sit dolore.','numquam','http://www.sit.com','Ipsum','180819',14,40,-26);
INSERT INTO "posts" VALUES(5,'Magnam numquam consectetur voluptatem sed dolorem voluptatem','Modi quaerat magnam dolore tempora. Dolor quisquam aliquam dolorem sit. Eius modi eius eius modi. Tempora amet est non etincidunt magnam numquam sit. Est ut numquam magnam.','eius','http://www.aliquam.com','Est','000224',64,17,47);
INSERT INTO "posts" VALUES(6,'Voluptatem etincidunt amet aliquam amet numquam eius','Sit dolore non labore velit quaerat etincidunt. Dolore labore quisquam sit. Porro numquam magnam velit dolor labore. Tempora modi adipisci eius porro magnam aliquam. Consectetur sed dolorem dolor est amet tempora. Porro consectetur tempora quisquam ut. Dolorem ut sed modi dolorem dolorem. Etincidunt dolore magnam velit numquam ipsum eius. Dolore porro neque adipisci est velit.','sit','http://www.etincidunt.com','Sit','200106',36,19,17);
INSERT INTO "posts" VALUES(7,'Adipisci aliquam porro ipsum non velit','Velit labore labore dolor quiquia. Quisquam non etincidunt adipisci porro quisquam modi quiquia. Numquam ut consectetur adipisci ut eius labore modi. Amet non dolor ut quiquia. Adipisci modi dolorem consectetur amet. Neque labore labore adipisci porro magnam etincidunt.','aliquam','http://www.consectetur.com','Dolore','140626',5,12,-7);
INSERT INTO "posts" VALUES(8,'Quisquam ut modi velit dolor amet dolor','Non labore porro numquam quisquam numquam. Velit dolor tempora voluptatem porro labore voluptatem numquam. Adipisci ipsum modi quisquam dolorem adipisci dolore. Etincidunt neque aliquam magnam porro dolor. Non quaerat etincidunt sit labore eius sed amet. Sit sit numquam eius quiquia dolorem ut. Numquam tempora ipsum dolore est est eius ut.','sed','http://www.tempora.com','Etincidunt','131125',76,10,66);
INSERT INTO "posts" VALUES(9,'Etincidunt adipisci voluptatem ut etincidunt porro sit','Sit adipisci amet ut labore aliquam ut quisquam. Neque magnam dolor velit neque. Dolore eius amet labore ut non adipisci quisquam. Sit aliquam modi dolor. Consectetur neque non etincidunt. Ut ut neque consectetur etincidunt. Sed quiquia aliquam aliquam consectetur etincidunt magnam. Etincidunt velit quiquia quisquam non dolorem tempora.','est','http://www.neque.com','Consectetur','050717',69,4,65);
INSERT INTO "posts" VALUES(10,'Quiquia porro voluptatem dolorem','Dolorem magnam eius est etincidunt. Labore ipsum quiquia quiquia porro ipsum modi. Modi quisquam numquam adipisci. Etincidunt quaerat porro modi aliquam voluptatem porro. Dolor modi consectetur neque dolore sit voluptatem.','etincidunt','http://www.eius.com','Neque','061211',34,29,5);
INSERT INTO "posts" VALUES(11,'Sed velit labore non velit non ipsum','Sed est labore magnam neque quiquia sit quiquia. Etincidunt dolorem voluptatem amet. Voluptatem numquam est dolore etincidunt. Labore velit non labore labore quisquam adipisci etincidunt. Etincidunt voluptatem est quisquam magnam sed. Ut tempora consectetur numquam modi dolorem velit.','quiquia','http://www.modi.com','Tempora','110623',93,6,87);
INSERT INTO "posts" VALUES(12,'Quaerat neque est ut dolore amet numquam porro','Neque quaerat quaerat sit. Dolorem numquam adipisci quaerat sed ut etincidunt. Amet magnam adipisci sit consectetur non amet. Sit ipsum amet quiquia quaerat quaerat sit. Sed neque magnam labore labore sit magnam. Eius voluptatem dolore dolor dolorem. Labore dolorem dolorem tempora ut. Dolor est ipsum sit dolore velit porro. Etincidunt numquam adipisci ipsum sit quiquia quaerat.','adipisci','http://www.non.com','Sed','050123',82,6,76);
INSERT INTO "posts" VALUES(13,'Quisquam tempora etincidunt sed quisquam quisquam ipsum','Non non est neque modi dolorem non. Adipisci ipsum numquam non eius. Etincidunt sed sit consectetur aliquam ipsum amet. Velit non adipisci ut. Sed porro numquam dolor. Labore voluptatem quaerat eius adipisci porro ipsum dolor.','quiquia','http://www.porro.com','Quisquam','060820',27,42,-15);
INSERT INTO "posts" VALUES(14,'Consectetur dolorem dolor ut velit','Etincidunt dolor numquam sed eius. Quisquam consectetur voluptatem sit. Voluptatem amet ipsum etincidunt magnam dolorem. Sit magnam etincidunt ut numquam non eius numquam. Modi dolorem quisquam dolore ipsum ut porro sed. Magnam tempora etincidunt non numquam. Amet dolore quisquam neque ut quiquia. Est sit dolore neque amet etincidunt sit. Dolore ipsum labore adipisci ipsum consectetur tempora.','voluptatem','http://www.consectetur.com','Est','090524',96,8,88);
INSERT INTO "posts" VALUES(15,'Ut sed est adipisci amet quiquia numquam sit','Labore numquam modi voluptatem est adipisci numquam ut. Modi dolor amet modi sed ut labore dolor. Ut ipsum labore dolorem quaerat adipisci est. Dolore sit velit aliquam eius tempora quiquia. Ut neque ipsum modi est dolore. Tempora adipisci labore labore quaerat tempora neque.','ut','http://www.neque.com','Numquam','200210',89,47,42);
INSERT INTO "posts" VALUES(16,'Tempora numquam est numquam porro etincidunt dolor est','Quiquia labore magnam quisquam. Tempora sed quisquam eius quisquam quaerat. Labore quiquia quisquam quaerat. Quiquia ipsum quiquia dolor sit numquam etincidunt. Voluptatem ut quaerat magnam numquam velit quisquam. Porro dolor consectetur tempora ipsum etincidunt consectetur velit. Amet adipisci neque dolor voluptatem labore.','ipsum','http://www.dolore.com','Dolore','141018',57,17,40);
INSERT INTO "posts" VALUES(17,'Labore amet dolor ipsum etincidunt quiquia','Labore sit quaerat est etincidunt. Sit quaerat quiquia neque sed magnam etincidunt. Porro quaerat amet est quaerat labore voluptatem est. Etincidunt labore quiquia neque voluptatem. Quaerat quaerat velit voluptatem neque amet aliquam sed. Tempora etincidunt eius neque dolore. Quiquia dolore ut aliquam tempora etincidunt porro dolor. Quisquam neque neque dolorem numquam dolore etincidunt eius. Dolorem neque tempora modi.','amet','http://www.etincidunt.com','Modi','020224',81,22,59);
INSERT INTO "posts" VALUES(18,'Sed quaerat quaerat magnam sed','Neque ut quisquam amet. Labore quisquam sed quisquam magnam. Velit sit sed magnam amet quaerat magnam. Modi amet non labore. Quaerat eius quisquam dolore voluptatem velit ut adipisci. Sed dolore consectetur est dolorem neque. Quiquia magnam modi neque amet. Sed velit eius tempora velit porro amet magnam. Modi dolorem quaerat ut sit modi dolorem dolorem. Consectetur adipisci aliquam sit eius.','numquam','http://www.sed.com','Modi','151231',40,10,30);
INSERT INTO "posts" VALUES(19,'Quaerat ut porro aliquam adipisci tempora','Etincidunt velit consectetur eius porro dolorem adipisci est. Ut dolore adipisci tempora amet eius numquam. Magnam quaerat numquam ut etincidunt. Neque quisquam est sit amet. Eius voluptatem sit ipsum. Velit ut labore ipsum consectetur non.','porro','http://www.neque.com','Modi','180423',81,27,54);
INSERT INTO "posts" VALUES(20,'Etincidunt dolore est etincidunt amet','Sit velit aliquam dolorem. Dolorem non porro est modi magnam voluptatem voluptatem. Dolorem etincidunt magnam modi quaerat aliquam etincidunt. Magnam labore quaerat porro est. Consectetur porro quiquia voluptatem labore. Ut consectetur ut sit etincidunt quaerat consectetur consectetur. Ipsum neque est etincidunt dolore velit quisquam non. Voluptatem amet numquam quaerat modi magnam tempora.','sed','http://www.dolore.com','Quisquam','061211',50,17,33);
INSERT INTO "posts" VALUES(21,'Quaerat ut etincidunt dolorem etincidunt','Neque quiquia neque ut sed sed. Dolorem ipsum sed quaerat sit eius sed etincidunt. Dolorem tempora ut dolorem dolore. Ipsum modi ipsum quisquam numquam voluptatem non quiquia. Modi aliquam etincidunt consectetur dolore ipsum eius. Labore modi ipsum aliquam numquam porro. Sit dolor neque quisquam. Quisquam magnam dolor tempora velit numquam porro ut. Voluptatem ut voluptatem aliquam quiquia numquam.','neque','http://www.modi.com','Modi','101226',63,5,58);
INSERT INTO "posts" VALUES(22,'Est velit est quaerat','Eius dolore aliquam ut tempora tempora. Adipisci magnam est numquam neque. Quisquam dolore sed etincidunt tempora modi numquam. Numquam quisquam numquam amet quaerat. Dolore sed neque tempora velit ipsum tempora quiquia. Magnam etincidunt porro ipsum est est.','est','http://www.porro.com','Dolorem','131014',45,34,11);
INSERT INTO "posts" VALUES(23,'Velit ipsum etincidunt dolorem sed magnam','Neque magnam magnam modi numquam tempora velit. Sit quaerat tempora est. Quisquam consectetur porro ut est magnam numquam. Magnam adipisci sit ut aliquam neque. Eius etincidunt labore tempora magnam sed labore. Voluptatem velit dolore voluptatem numquam. Ut dolore neque sit quisquam quaerat neque sit. Non dolor porro non ipsum amet quisquam neque. Non voluptatem neque sed dolorem eius.','adipisci','http://www.aliquam.com','Dolor','070101',87,42,45);
INSERT INTO "posts" VALUES(24,'Consectetur numquam aliquam amet velit magnam neque aliquam','Tempora est velit numquam tempora quaerat sed. Dolor consectetur modi sed. Voluptatem velit non neque dolorem sit porro. Porro adipisci non non modi neque quaerat. Dolor ipsum sit porro numquam. Magnam porro etincidunt voluptatem labore porro amet. Sed tempora non est eius quiquia dolore. Sed velit eius dolorem adipisci labore. Ut consectetur consectetur non voluptatem magnam.','consectetur','http://www.modi.com','Magnam','110305',48,43,5);
INSERT INTO "posts" VALUES(25,'Porro quisquam sed sit quaerat consectetur sed','Non sit ipsum numquam labore ipsum. Sed labore ipsum velit numquam eius sed. Non etincidunt non labore aliquam dolorem. Aliquam velit numquam dolorem numquam non non. Ipsum etincidunt porro ipsum adipisci. Quisquam tempora quaerat quisquam quaerat amet porro voluptatem. Non neque non adipisci numquam consectetur neque ipsum. Dolorem labore amet quaerat. Numquam sed ut numquam dolore dolore. Est labore ipsum sed etincidunt labore sed.','numquam','http://www.velit.com','Tempora','001027',78,6,72);
INSERT INTO "posts" VALUES(26,'Quisquam aliquam sit etincidunt quiquia neque dolor','Neque voluptatem voluptatem voluptatem quiquia. Tempora adipisci magnam labore ut etincidunt. Non dolore voluptatem dolor porro modi. Dolor quisquam labore magnam velit. Consectetur numquam sed porro. Ut adipisci labore consectetur dolore aliquam. Numquam aliquam quaerat tempora est magnam. Quaerat tempora labore eius etincidunt quisquam ipsum. Quisquam velit tempora dolor labore magnam.','sed','http://www.velit.com','Tempora','181124',14,36,-22);
INSERT INTO "posts" VALUES(27,'Dolore sed velit labore eius','Quaerat velit modi porro amet quiquia voluptatem. Est quiquia amet neque consectetur consectetur dolore amet. Est non quisquam dolorem amet. Porro ut dolor etincidunt non velit. Amet dolor dolore modi dolorem. Adipisci est non est. Quaerat non quaerat etincidunt sed.','dolor','http://www.velit.com','Ut','190709',63,24,39);
INSERT INTO "posts" VALUES(28,'Sed dolor dolorem dolore est','Sit ipsum quisquam ut modi quaerat. Eius sit voluptatem aliquam dolore velit dolor quiquia. Adipisci sit amet adipisci non aliquam labore. Sed eius numquam quaerat. Amet ipsum sit non velit consectetur. Porro quisquam etincidunt est sit neque. Ut quiquia est ipsum adipisci neque. Dolore eius sit quisquam amet amet. Dolore numquam dolore numquam aliquam sit ipsum voluptatem. Dolor porro velit tempora porro aliquam.','dolorem','http://www.ipsum.com','Labore','131023',52,20,32);
INSERT INTO "posts" VALUES(29,'Ut dolorem labore quisquam consectetur etincidunt velit','Quisquam sed neque quiquia magnam quisquam. Magnam sit eius sed. Consectetur quisquam eius quaerat adipisci. Velit neque neque quaerat etincidunt ut eius dolorem. Voluptatem adipisci labore aliquam adipisci. Consectetur neque quaerat sed aliquam.','ut','http://www.sed.com','Sit','190910',33,10,23);
INSERT INTO "posts" VALUES(30,'Ipsum est sit quaerat eius aliquam quiquia ipsum','Est aliquam adipisci sit quisquam etincidunt. Aliquam quaerat porro ut. Numquam labore adipisci dolorem non. Ut magnam adipisci labore modi non non neque. Quisquam sit velit quiquia quiquia non ut. Est neque quisquam dolore dolore. Porro est dolorem quisquam sit. Non amet quaerat est magnam. Porro etincidunt quisquam sed sit dolor quaerat.','dolorem','http://www.aliquam.com','Velit','100522',40,25,15);
INSERT INTO "posts" VALUES(31,'Voluptatem quisquam quaerat adipisci','Numquam tempora voluptatem numquam eius velit etincidunt. Magnam ipsum neque sit adipisci. Etincidunt numquam sit eius. Numquam consectetur dolorem quisquam magnam consectetur sed. Non adipisci labore consectetur est eius quiquia. Velit porro adipisci dolore est quaerat voluptatem. Sed dolore etincidunt etincidunt porro quiquia. Ut non ut consectetur ut. Quisquam adipisci consectetur neque dolorem est eius. Quaerat est non dolorem non.','velit','http://www.numquam.com','Adipisci','060515',38,18,20);
INSERT INTO "posts" VALUES(32,'Velit neque ut quisquam voluptatem eius ut labore','Voluptatem est ut neque sed ut sed. Etincidunt dolorem velit neque etincidunt eius sit eius. Voluptatem modi dolore quiquia dolor modi. Ipsum non aliquam adipisci consectetur modi dolorem. Dolorem dolor consectetur quiquia amet labore voluptatem.','numquam','http://www.ipsum.com','Ipsum','190528',4,45,-41);
INSERT INTO "posts" VALUES(33,'Amet magnam modi est sit voluptatem magnam ut','Dolor ipsum porro voluptatem ut. Velit dolor consectetur velit numquam eius. Quaerat consectetur dolore non velit. Quiquia dolor dolor sit quiquia. Adipisci est magnam quaerat aliquam. Etincidunt voluptatem eius dolorem ipsum. Quiquia labore quaerat non amet amet. Modi aliquam quiquia sit. Dolorem velit dolore ut. Est dolor quiquia etincidunt.','neque','http://www.neque.com','Consectetur','091102',79,34,45);
INSERT INTO "posts" VALUES(34,'Labore dolore labore dolor etincidunt adipisci','Quaerat modi ipsum dolorem eius etincidunt etincidunt. Sit sit non numquam ut sit etincidunt. Quaerat dolorem sed numquam. Quisquam ut adipisci sed. Modi velit aliquam sit sit eius quisquam. Dolore velit consectetur quiquia voluptatem. Dolor aliquam etincidunt quaerat. Eius dolore consectetur sed quisquam.','neque','http://www.voluptatem.com','Magnam','020508',53,46,7);
INSERT INTO "posts" VALUES(35,'Sed consectetur consectetur consectetur quisquam','Aliquam numquam non velit. Quiquia dolore est magnam dolore modi. Etincidunt numquam neque quaerat dolore dolore quiquia. Ut sit consectetur sit adipisci ut eius numquam. Ipsum numquam porro adipisci adipisci. Quisquam sed sed magnam eius non est. Dolor quaerat quisquam dolorem est ut. Ipsum magnam voluptatem est quisquam. Quiquia ut velit sed consectetur dolor quaerat.','quiquia','http://www.consectetur.com','Eius','190408',17,7,10);
INSERT INTO "posts" VALUES(36,'Velit velit tempora amet eius','Eius quaerat velit neque. Magnam consectetur numquam non magnam sit. Modi est labore sed. Modi non etincidunt ut modi ut amet dolor. Adipisci sit porro porro non voluptatem. Amet neque amet voluptatem quiquia quiquia sit tempora. Sit ut dolorem non dolorem. Ut quaerat ipsum non. Magnam eius sit ipsum. Non dolorem ipsum quaerat quaerat quisquam aliquam consectetur.','sed','http://www.eius.com','Dolor','060704',41,20,21);
INSERT INTO "posts" VALUES(37,'Dolore sed quiquia magnam porro','Adipisci velit eius dolore aliquam adipisci. Porro quiquia tempora amet velit neque. Amet aliquam non voluptatem tempora sed consectetur. Velit dolor est neque dolor tempora tempora. Adipisci aliquam consectetur numquam numquam. Eius dolore numquam neque adipisci adipisci. Amet dolore aliquam consectetur ut etincidunt. Labore quisquam quisquam quiquia non aliquam ut. Adipisci dolore dolore quiquia dolorem est.','non','http://www.adipisci.com','Quiquia','200128',78,48,30);
INSERT INTO "posts" VALUES(38,'Velit ipsum quaerat quisquam sit','Ut velit velit sit dolorem numquam. Eius sit quiquia velit aliquam. Dolore numquam numquam quiquia labore. Dolor sed eius quiquia ut etincidunt neque sit. Tempora amet adipisci dolor neque. Dolor magnam sit quiquia ipsum labore. Sed magnam voluptatem tempora. Adipisci voluptatem dolor amet quaerat magnam ut. Neque quiquia ut sed modi dolore dolorem. Sit neque voluptatem aliquam voluptatem.','neque','http://www.voluptatem.com','Sed','111210',60,12,48);
INSERT INTO "posts" VALUES(39,'Velit sit dolor dolorem consectetur velit dolore sed','Quiquia labore velit voluptatem quisquam quaerat. Amet consectetur quaerat dolorem. Sit amet voluptatem non amet quaerat adipisci labore. Porro labore aliquam quiquia neque. Dolor etincidunt porro dolore velit aliquam. Neque amet labore consectetur voluptatem modi sit amet. Eius dolor sit voluptatem modi. Neque eius dolorem quaerat sed ipsum voluptatem quaerat. Ut aliquam eius consectetur modi tempora voluptatem.','numquam','http://www.neque.com','Ipsum','110721',63,2,61);
INSERT INTO "posts" VALUES(40,'Ipsum dolor ut tempora amet eius','Porro consectetur voluptatem tempora etincidunt neque numquam ipsum. Velit sit ipsum dolorem quiquia. Eius ipsum dolor labore. Quisquam quiquia numquam etincidunt neque non. Tempora adipisci dolore etincidunt velit eius voluptatem ipsum.','porro','http://www.sit.com','Etincidunt','130321',62,22,40);
INSERT INTO "posts" VALUES(41,'Amet sit quaerat amet dolore','Numquam porro magnam ut eius sit velit sit. Etincidunt est non modi. Porro porro voluptatem neque quisquam magnam ut dolorem. Amet quaerat eius porro. Amet neque aliquam quaerat dolore eius quaerat. Eius quisquam porro tempora. Adipisci sit tempora numquam numquam. Dolorem adipisci dolor amet quaerat. Dolor voluptatem adipisci tempora ipsum neque eius. Non labore porro sit adipisci.','dolor','http://www.ut.com','Magnam','020515',99,23,76);
INSERT INTO "posts" VALUES(42,'Quaerat dolor est amet','Velit dolor modi ut sit quaerat. Amet amet quiquia tempora dolore. Quisquam porro dolore dolore magnam. Labore etincidunt non aliquam. Aliquam non quiquia etincidunt sit ut aliquam tempora.','dolore','http://www.consectetur.com','Tempora','000516',42,50,-8);
INSERT INTO "posts" VALUES(43,'Labore dolore modi quaerat quisquam ipsum consectetur dolor','Ipsum tempora voluptatem sit adipisci amet porro. Neque eius magnam amet. Ipsum dolorem neque dolorem. Quisquam quiquia eius eius sit quisquam. Modi tempora neque dolorem dolorem ut. Modi voluptatem neque amet amet velit labore. Numquam dolorem modi magnam dolor quaerat numquam. Neque sed dolore labore etincidunt labore modi. Amet etincidunt ipsum dolorem etincidunt modi.','sed','http://www.non.com','Numquam','000629',87,21,66);
INSERT INTO "posts" VALUES(44,'Quaerat porro voluptatem velit voluptatem consectetur est neque','Porro dolorem dolore labore non voluptatem. Voluptatem tempora etincidunt sit aliquam. Dolorem tempora neque dolorem sed. Ipsum porro velit porro magnam adipisci magnam dolore. Numquam ipsum sed porro non consectetur amet.','eius','http://www.non.com','Tempora','180512',77,28,49);
INSERT INTO "posts" VALUES(45,'Ipsum labore tempora voluptatem adipisci non','Numquam consectetur consectetur dolorem dolorem voluptatem ipsum. Ut numquam ipsum non. Adipisci non ut quaerat velit eius. Dolorem porro etincidunt etincidunt. Numquam velit numquam est voluptatem.','aliquam','http://www.sed.com','Dolore','110324',95,46,49);
INSERT INTO "posts" VALUES(46,'Dolorem adipisci ipsum est','Numquam consectetur adipisci consectetur labore. Consectetur magnam eius quaerat tempora aliquam. Porro neque quisquam eius quisquam sit ipsum. Tempora porro labore dolor neque. Consectetur quisquam sit magnam etincidunt ipsum magnam. Amet modi sed quisquam. Adipisci dolorem tempora neque quisquam numquam sit. Aliquam dolore quisquam quiquia numquam adipisci est. Eius tempora sit ut.','dolorem','http://www.etincidunt.com','Labore','170413',8,0,8);
INSERT INTO "posts" VALUES(47,'Porro voluptatem sed non neque ut','Adipisci est labore modi. Ut tempora numquam porro quiquia dolor quaerat. Ipsum porro eius labore quaerat voluptatem numquam dolorem. Porro numquam aliquam adipisci sit adipisci dolorem numquam. Porro numquam porro consectetur aliquam magnam. Labore amet dolorem sed. Magnam est velit eius est modi etincidunt. Etincidunt velit tempora velit quiquia consectetur dolorem.','etincidunt','http://www.non.com','Adipisci','000407',5,27,-22);
INSERT INTO "posts" VALUES(48,'Tempora ut voluptatem dolore','Quaerat ut magnam magnam ut. Sit quiquia porro etincidunt numquam. Quaerat magnam dolor quiquia velit. Dolorem quaerat labore sit quiquia. Quisquam sit quaerat modi voluptatem. Neque porro etincidunt quisquam. Adipisci est dolorem eius.','labore','http://www.sed.com','Consectetur','020704',22,21,1);
INSERT INTO "posts" VALUES(49,'Voluptatem non etincidunt labore','Non voluptatem quiquia magnam non. Velit non ipsum non quiquia neque sed. Sed porro est porro. Modi tempora amet sit numquam. Porro velit non aliquam tempora ut neque. Tempora eius consectetur eius dolore consectetur. Quisquam velit porro quisquam.','ut','http://www.non.com','Porro','040729',67,32,35);
INSERT INTO "posts" VALUES(50,'Sit dolor porro sit modi','Numquam voluptatem adipisci quisquam quiquia eius tempora est. Adipisci adipisci amet velit. Etincidunt ipsum quisquam velit amet dolorem numquam dolore. Voluptatem non porro dolore quaerat etincidunt. Voluptatem voluptatem ipsum numquam quiquia modi quiquia amet. Modi tempora est est ut consectetur velit. Sed quisquam quisquam velit etincidunt consectetur tempora aliquam. Magnam quaerat numquam aliquam.','amet','http://www.adipisci.com','Eius','180908',16,27,-11);
INSERT INTO "posts" VALUES(51,'Quiquia quaerat dolorem eius consectetur adipisci','Amet etincidunt quaerat porro magnam voluptatem est. Quisquam neque dolor quiquia. Amet sed numquam dolor. Quisquam quiquia modi quiquia porro quiquia. Dolor modi quiquia dolorem porro quisquam est. Tempora dolor etincidunt magnam. Velit voluptatem porro sed porro ipsum numquam.','adipisci','http://www.amet.com','Quisquam','151218',19,13,6);
INSERT INTO "posts" VALUES(52,'Eius est dolor velit dolore','Dolore ut sit velit. Quaerat porro modi porro. Adipisci dolor voluptatem quiquia amet etincidunt numquam. Amet aliquam velit consectetur adipisci. Eius labore quisquam etincidunt. Quisquam dolore quisquam labore velit labore. Neque ut voluptatem velit quiquia neque. Est modi amet quisquam amet.','eius','http://www.quaerat.com','Est','070409',82,48,34);
INSERT INTO "posts" VALUES(53,'Dolor sit dolorem adipisci sit','Consectetur amet consectetur magnam adipisci dolorem. Porro sit etincidunt modi aliquam. Quaerat ut quaerat eius. Sed adipisci quiquia dolorem ipsum labore. Etincidunt quisquam est dolore voluptatem sed est sit. Etincidunt voluptatem etincidunt porro numquam.','modi','http://www.tempora.com','Sit','160322',50,13,37);
INSERT INTO "posts" VALUES(54,'Quiquia aliquam ut modi modi','Sit est numquam sit labore. Adipisci numquam modi quisquam tempora. Labore sed adipisci quisquam. Eius aliquam ipsum est sit est. Tempora dolor consectetur adipisci velit. Dolore quaerat quiquia numquam. Dolor velit ipsum porro.','amet','http://www.adipisci.com','Amet','050216',52,19,33);
INSERT INTO "posts" VALUES(55,'Quaerat dolore adipisci non tempora tempora','Sit consectetur eius aliquam adipisci magnam. Dolor ipsum ut modi quiquia tempora quisquam voluptatem. Est est quaerat sed porro. Neque tempora consectetur est consectetur. Ut eius dolore magnam est ipsum. Quiquia porro magnam adipisci consectetur. Ut etincidunt eius porro porro dolor.','ut','http://www.quaerat.com','Labore','141027',63,43,20);
INSERT INTO "posts" VALUES(56,'Aliquam non magnam ut tempora sed voluptatem','Tempora modi ut numquam dolore porro. Ut sit voluptatem etincidunt ut sit etincidunt neque. Ut voluptatem labore est eius aliquam quaerat. Quaerat sit quiquia etincidunt aliquam porro quiquia. Amet numquam porro quisquam ipsum non voluptatem. Non quaerat non quisquam labore. Porro tempora magnam eius quisquam quaerat consectetur modi. Aliquam modi voluptatem modi etincidunt velit velit est. Ut porro amet eius ut.','etincidunt','http://www.adipisci.com','Consectetur','020314',3,47,-44);
INSERT INTO "posts" VALUES(57,'Etincidunt aliquam non ipsum non labore aliquam','Adipisci quiquia sed non. Quiquia est eius consectetur dolorem modi porro. Magnam dolorem consectetur modi voluptatem. Magnam numquam est non dolore quaerat sit velit. Ipsum modi est quisquam dolorem est quiquia. Velit neque tempora neque. Dolor porro amet consectetur sit adipisci quiquia labore. Etincidunt dolorem voluptatem numquam dolore non non dolorem. Velit neque ipsum sit quaerat.','eius','http://www.amet.com','Numquam','070407',72,6,66);
INSERT INTO "posts" VALUES(58,'Porro quaerat modi neque ut sit','Dolorem dolore numquam quisquam quiquia quiquia aliquam consectetur. Ipsum modi aliquam sit sit dolorem dolorem dolorem. Ipsum labore labore neque sit tempora. Labore aliquam etincidunt velit. Eius ut non sit dolor eius dolore adipisci. Quiquia porro labore porro quaerat. Voluptatem quaerat numquam ut modi porro. Non ipsum numquam amet tempora dolorem numquam dolorem. Dolor eius est ut. Etincidunt dolor modi consectetur porro aliquam est.','dolorem','http://www.ut.com','Ipsum','130810',3,49,-46);
INSERT INTO "posts" VALUES(59,'Etincidunt sit sed consectetur porro est labore labore','Dolor dolorem ut adipisci dolore voluptatem. Dolore sed porro adipisci ut sed. Adipisci sit est velit ipsum. Quisquam eius adipisci tempora dolore. Ipsum adipisci numquam voluptatem dolor porro. Tempora est sit quaerat quaerat etincidunt aliquam eius. Tempora eius eius quiquia magnam. Quaerat magnam etincidunt est modi dolor.','dolor','http://www.porro.com','Dolor','160528',5,49,-44);
INSERT INTO "posts" VALUES(60,'Eius dolorem ipsum magnam ipsum quaerat non','Sed etincidunt modi adipisci. Numquam dolorem labore ipsum eius. Labore sit quaerat voluptatem velit consectetur adipisci. Ut magnam ipsum non eius dolore adipisci. Voluptatem sit quisquam quisquam neque. Porro sed est consectetur magnam porro etincidunt.','magnam','http://www.quaerat.com','Velit','160908',21,0,21);
INSERT INTO "posts" VALUES(61,'Quisquam modi etincidunt magnam aliquam','Sed quaerat magnam quiquia quisquam dolore porro dolor. Tempora consectetur magnam est labore. Consectetur neque sed est dolore dolorem etincidunt. Amet numquam voluptatem non. Est velit dolore quaerat porro velit. Neque labore etincidunt sed quisquam tempora aliquam.','adipisci','http://www.ut.com','Sit','201214',24,50,-26);
INSERT INTO "posts" VALUES(62,'Quiquia neque tempora neque dolor labore sit','Numquam modi numquam sit eius labore. Amet ipsum adipisci quiquia amet magnam consectetur labore. Eius ipsum dolorem dolorem neque. Porro non velit magnam. Quiquia consectetur non amet magnam porro sit numquam. Porro sit consectetur porro. Tempora voluptatem dolor tempora ut consectetur magnam. Ut tempora dolore velit magnam.','quaerat','http://www.labore.com','Amet','050322',98,43,55);
INSERT INTO "posts" VALUES(63,'Velit dolor numquam ipsum consectetur magnam','Est dolor velit dolore modi est. Ipsum dolor dolor neque eius sed modi. Sit dolorem quiquia eius quisquam dolor. Tempora labore dolor aliquam amet tempora. Sit velit voluptatem adipisci magnam. Dolorem voluptatem ipsum adipisci modi tempora. Quiquia tempora adipisci quisquam ut est. Porro ipsum ut eius quiquia velit.','aliquam','http://www.magnam.com','Consectetur','141116',45,49,-4);
INSERT INTO "posts" VALUES(64,'Quiquia dolor ipsum est porro modi quaerat','Dolorem adipisci eius sed sit eius voluptatem. Modi est quaerat quaerat ut quiquia. Dolore numquam voluptatem dolor magnam. Quisquam porro tempora quiquia dolorem dolore. Modi dolore labore eius consectetur eius dolore porro. Quiquia aliquam neque consectetur dolorem modi porro. Dolor dolorem adipisci etincidunt ipsum ut. Neque eius dolore ut ipsum porro neque. Eius quaerat eius porro amet. Amet sit labore aliquam numquam quisquam ut quiquia.','ut','http://www.eius.com','Etincidunt','090110',63,49,14);
INSERT INTO "posts" VALUES(65,'Eius dolore modi etincidunt dolor','Dolor labore quaerat quaerat modi sit magnam voluptatem. Dolore quiquia neque voluptatem dolor quiquia aliquam porro. Etincidunt quiquia modi voluptatem consectetur. Non consectetur etincidunt adipisci est. Velit dolore voluptatem velit etincidunt neque consectetur. Eius tempora aliquam modi ipsum amet adipisci quisquam. Modi tempora quaerat aliquam amet voluptatem etincidunt. Quisquam dolorem eius sit dolore.','sed','http://www.numquam.com','Tempora','180808',64,7,57);
INSERT INTO "posts" VALUES(66,'Tempora magnam voluptatem eius','Sit sed consectetur consectetur quisquam. Voluptatem voluptatem magnam ut magnam neque sit modi. Labore ut voluptatem porro. Aliquam numquam magnam quaerat consectetur sed labore aliquam. Magnam ipsum quaerat est labore velit adipisci quaerat.','velit','http://www.non.com','Tempora','020430',24,26,-2);
INSERT INTO "posts" VALUES(67,'Magnam quisquam labore numquam eius consectetur etincidunt quisquam','Magnam consectetur quisquam adipisci. Amet sit labore sit labore ipsum ut. Voluptatem labore eius quiquia aliquam modi sed. Modi aliquam numquam labore amet aliquam aliquam amet. Quiquia adipisci porro non. Numquam quaerat sed eius eius.','quiquia','http://www.ut.com','Est','050228',100,1,99);
INSERT INTO "posts" VALUES(68,'Ipsum amet porro quisquam modi magnam amet','Non etincidunt ipsum sit quisquam ipsum labore amet. Non quisquam eius sit etincidunt est adipisci. Dolorem sed aliquam magnam porro. Quisquam dolorem quisquam sed eius dolorem. Velit tempora etincidunt magnam quiquia eius voluptatem ut.','eius','http://www.ut.com','Velit','050817',57,31,26);
INSERT INTO "posts" VALUES(69,'Quiquia non numquam adipisci','Sed dolore adipisci ipsum eius ut non non. Est amet amet porro ut. Dolore adipisci consectetur non non dolorem. Magnam aliquam numquam voluptatem velit neque porro magnam. Dolorem aliquam sed magnam etincidunt eius magnam dolore. Quiquia voluptatem ipsum numquam. Voluptatem magnam non ut. Dolore adipisci quisquam ut.','dolor','http://www.dolore.com','Porro','150210',30,16,14);
INSERT INTO "posts" VALUES(70,'Dolore amet quisquam amet','Eius dolorem dolore amet numquam consectetur dolorem. Aliquam ut est non porro adipisci quaerat amet. Voluptatem numquam dolor eius dolor est. Magnam quisquam dolore consectetur amet dolore neque dolorem. Voluptatem dolorem ut porro eius numquam. Quaerat velit voluptatem sed aliquam aliquam. Dolor aliquam magnam consectetur aliquam modi sit voluptatem. Consectetur quisquam non voluptatem. Quaerat consectetur sed quaerat quisquam.','ut','http://www.quisquam.com','Tempora','161014',31,3,28);
INSERT INTO "posts" VALUES(71,'Numquam sed amet voluptatem dolor numquam quaerat magnam','Sit quisquam numquam tempora sit. Quiquia sit adipisci sed numquam non. Est quaerat aliquam ut dolorem neque labore quaerat. Quisquam modi eius velit eius sit dolorem. Dolore est labore quaerat ut. Quisquam dolor adipisci non labore numquam magnam dolore. Sit consectetur sed modi eius voluptatem. Dolorem quaerat modi labore quiquia magnam eius.','modi','http://www.porro.com','Quisquam','181027',97,14,83);
INSERT INTO "posts" VALUES(72,'Adipisci quisquam sit adipisci voluptatem dolorem non','Consectetur sit adipisci dolorem modi porro dolore non. Consectetur labore sed amet numquam amet tempora. Dolorem porro est sed quisquam. Sed consectetur neque magnam ut non neque. Magnam dolor amet modi. Amet labore modi tempora adipisci dolorem numquam. Amet quisquam quisquam quisquam adipisci ut sed sit. Voluptatem voluptatem neque dolor consectetur etincidunt.','ut','http://www.quaerat.com','Neque','070716',30,49,-19);
INSERT INTO "posts" VALUES(73,'Non aliquam dolore labore adipisci dolor porro voluptatem','Magnam neque etincidunt dolor est. Dolore dolor etincidunt quisquam. Porro etincidunt etincidunt modi eius non est voluptatem. Aliquam non sed labore. Neque porro tempora est porro quiquia. Quisquam quaerat amet neque etincidunt consectetur est neque.','voluptatem','http://www.velit.com','Velit','001117',80,24,56);
INSERT INTO "posts" VALUES(74,'Modi quiquia quisquam dolore magnam dolorem est consectetur','Ipsum quaerat quisquam quaerat dolore labore modi. Dolorem sed voluptatem amet dolore adipisci numquam. Dolore numquam sit numquam etincidunt. Sed consectetur est dolor ipsum dolore est. Quaerat aliquam magnam labore velit quaerat non. Ut sit voluptatem consectetur quiquia etincidunt modi.','non','http://www.ipsum.com','Quisquam','130509',73,31,42);
INSERT INTO "posts" VALUES(75,'Velit ipsum ipsum est magnam amet etincidunt etincidunt','Amet labore labore etincidunt. Neque quiquia amet voluptatem eius. Tempora non est sit velit amet. Etincidunt non est porro non consectetur etincidunt. Porro amet etincidunt ipsum sed modi. Quisquam sed aliquam ipsum quaerat. Numquam adipisci dolor eius dolorem. Quisquam adipisci amet non voluptatem velit tempora. Amet est sit neque tempora quaerat tempora numquam. Ut ipsum sed modi ipsum dolor voluptatem non.','quisquam','http://www.etincidunt.com','Eius','140817',14,9,5);
INSERT INTO "posts" VALUES(76,'Quiquia dolore labore porro sit eius porro dolore','Eius quaerat dolore labore. Aliquam voluptatem velit dolor magnam ut ut. Magnam ut tempora consectetur modi amet neque. Quaerat quisquam quisquam porro dolore dolorem ipsum. Labore sit modi voluptatem ipsum eius. Etincidunt amet neque eius est quisquam dolor. Aliquam consectetur numquam quaerat. Ut voluptatem quisquam est. Eius eius voluptatem consectetur porro porro est quaerat.','dolore','http://www.velit.com','Porro','000402',68,37,31);
INSERT INTO "posts" VALUES(77,'Quiquia numquam adipisci quisquam','Adipisci quiquia velit numquam tempora dolorem quiquia. Dolore consectetur ipsum neque. Numquam velit modi quiquia quiquia. Voluptatem numquam sit amet tempora labore adipisci sed. Modi quaerat sed velit magnam quisquam ipsum. Consectetur quisquam numquam porro quiquia labore neque. Adipisci labore tempora magnam adipisci dolor tempora modi. Consectetur dolore labore aliquam ut.','adipisci','http://www.consectetur.com','Consectetur','050128',53,39,14);
INSERT INTO "posts" VALUES(78,'Est labore dolore adipisci amet','Etincidunt porro aliquam non tempora modi. Labore magnam eius numquam. Voluptatem neque labore sed adipisci dolorem quaerat porro. Magnam modi numquam eius adipisci dolorem quisquam numquam. Modi non dolore etincidunt sed amet eius. Neque eius quisquam numquam sit etincidunt dolorem ipsum. Amet amet voluptatem quaerat ipsum quisquam. Tempora labore aliquam aliquam.','voluptatem','http://www.non.com','Neque','140420',7,42,-35);
INSERT INTO "posts" VALUES(79,'Dolor quisquam non velit eius neque ut','Consectetur aliquam eius amet est. Ipsum velit modi aliquam dolorem sit porro. Modi quaerat magnam dolore consectetur aliquam. Non quiquia sit dolor. Quaerat dolore numquam etincidunt magnam. Quisquam dolore eius adipisci aliquam ipsum ut consectetur. Dolore dolorem voluptatem eius quiquia tempora. Sit aliquam sit quiquia tempora tempora dolorem porro. Aliquam etincidunt eius dolor eius ut. Modi dolore magnam aliquam tempora neque labore.','amet','http://www.labore.com','Quiquia','110620',44,37,7);
INSERT INTO "posts" VALUES(80,'Sed sit aliquam quisquam eius consectetur quaerat dolorem','Numquam dolorem est amet magnam aliquam etincidunt. Voluptatem eius est numquam sit adipisci. Ipsum dolore non velit quiquia est quiquia sit. Porro quisquam labore amet dolor voluptatem dolore aliquam. Labore adipisci quaerat non porro quiquia. Porro modi ipsum ipsum. Tempora sit aliquam adipisci sit magnam ut modi.','quiquia','http://www.aliquam.com','Neque','030209',39,8,31);
INSERT INTO "posts" VALUES(81,'Velit etincidunt ipsum quisquam quisquam','Dolorem tempora numquam non. Voluptatem velit etincidunt non non amet. Amet eius amet etincidunt ipsum sit tempora. Dolore quisquam quisquam neque non ut. Aliquam quisquam ut porro quaerat etincidunt dolor quiquia. Amet sed est ut ut voluptatem consectetur. Magnam amet labore modi eius non. Dolorem sit voluptatem modi neque tempora numquam. Dolor quisquam numquam aliquam amet quaerat. Eius adipisci aliquam voluptatem non neque porro dolore.','aliquam','http://www.quiquia.com','Ipsum','160601',72,25,47);
INSERT INTO "posts" VALUES(82,'Non etincidunt dolorem dolorem dolor labore modi amet','Est consectetur ut neque consectetur non voluptatem quiquia. Labore quaerat amet quiquia non amet tempora sed. Modi porro aliquam amet amet. Dolore porro eius adipisci amet labore. Sed neque dolore voluptatem porro neque amet. Labore amet numquam sed labore non. Quiquia eius modi tempora voluptatem.','eius','http://www.porro.com','Dolorem','121014',53,23,30);
INSERT INTO "posts" VALUES(83,'Aliquam dolorem tempora sed ut','Dolorem quaerat dolore voluptatem velit dolor numquam eius. Sit quiquia dolor aliquam. Quisquam adipisci voluptatem sed amet. Velit aliquam aliquam tempora etincidunt tempora. Tempora quaerat ipsum ut non. Consectetur voluptatem eius amet ipsum non. Tempora dolore amet neque non quaerat voluptatem. Magnam quiquia quisquam porro ipsum dolor est amet.','consectetur','http://www.magnam.com','Amet','060822',50,7,43);
INSERT INTO "posts" VALUES(84,'Voluptatem ipsum amet sed','Tempora voluptatem aliquam quaerat numquam modi labore quaerat. Aliquam est aliquam est quaerat sed. Adipisci velit quiquia neque numquam dolor. Quiquia adipisci non consectetur. Modi porro aliquam tempora sit etincidunt. Quiquia amet amet labore dolorem.','velit','http://www.eius.com','Sed','150511',75,16,59);
INSERT INTO "posts" VALUES(85,'Sed adipisci etincidunt quaerat','Porro tempora sit dolor magnam. Non neque labore porro voluptatem. Numquam ipsum dolor neque tempora tempora etincidunt non. Etincidunt neque labore dolore dolore. Velit dolor amet porro quiquia.','amet','http://www.amet.com','Ipsum','081114',96,21,75);
INSERT INTO "posts" VALUES(86,'Voluptatem ut adipisci dolore quaerat neque neque neque','Est quisquam labore magnam neque quaerat eius. Sed non magnam labore dolorem sit. Est adipisci porro dolor. Non ipsum adipisci quisquam sit numquam. Aliquam quiquia etincidunt ut consectetur quaerat voluptatem labore. Dolor est ut quaerat aliquam sed numquam. Magnam consectetur dolor neque modi labore magnam. Aliquam non voluptatem quisquam.','sed','http://www.consectetur.com','Est','200512',17,16,1);
INSERT INTO "posts" VALUES(87,'Quisquam ut neque modi eius eius porro neque','Dolorem amet sit sed etincidunt numquam non. Labore est quisquam magnam quiquia magnam quisquam sed. Tempora velit quiquia dolorem non consectetur dolorem labore. Dolor modi magnam modi. Est ut ut tempora numquam. Dolore quaerat ut amet consectetur tempora est neque. Eius porro eius tempora voluptatem dolorem ut. Ipsum sit amet velit dolorem numquam. Tempora consectetur etincidunt neque.','est','http://www.quisquam.com','Dolorem','070703',58,8,50);
INSERT INTO "posts" VALUES(88,'Est quaerat amet porro modi consectetur consectetur','Adipisci quiquia dolore velit dolorem numquam voluptatem ipsum. Consectetur non etincidunt numquam ipsum voluptatem ut quisquam. Etincidunt dolorem modi tempora numquam modi adipisci quaerat. Eius sit eius velit neque aliquam amet ipsum. Porro non est ut porro neque. Ut sed quisquam quiquia.','porro','http://www.voluptatem.com','Adipisci','190218',25,3,22);
INSERT INTO "posts" VALUES(89,'Dolore sit consectetur neque aliquam ut quaerat','Modi eius etincidunt eius. Est quaerat dolorem numquam ipsum modi etincidunt. Labore sit est dolorem. Amet quisquam sit voluptatem. Ut labore dolorem ipsum neque sit porro numquam. Tempora sed sit dolorem. Est tempora velit modi. Ipsum quisquam quaerat neque est ut ipsum velit. Numquam amet modi velit numquam.','adipisci','http://www.dolorem.com','Modi','110218',73,46,27);
INSERT INTO "posts" VALUES(90,'Quisquam ipsum tempora voluptatem','Magnam magnam quiquia tempora amet. Aliquam modi labore labore magnam dolor labore neque. Eius consectetur adipisci aliquam dolorem magnam ipsum. Eius quaerat est magnam adipisci labore. Modi velit porro modi adipisci. Etincidunt numquam magnam eius tempora non quisquam quiquia. Neque ipsum sed velit sit ipsum numquam dolor. Neque sit est labore dolorem numquam. Dolore dolorem ipsum ut velit amet adipisci.','ut','http://www.consectetur.com','Sed','120802',12,31,-19);
INSERT INTO "posts" VALUES(91,'Adipisci aliquam consectetur aliquam est adipisci non','Etincidunt modi etincidunt modi eius eius. Aliquam modi est voluptatem modi velit. Non aliquam consectetur etincidunt neque neque magnam. Magnam modi dolorem etincidunt dolore consectetur neque ipsum. Quaerat sit consectetur non. Adipisci voluptatem adipisci dolore dolor quaerat dolor modi. Quisquam porro sit quiquia quaerat numquam modi. Ipsum voluptatem quaerat modi quiquia. Labore porro tempora non eius aliquam adipisci. Est sit ut magnam.','quisquam','http://www.dolor.com','Velit','120823',55,0,55);
INSERT INTO "posts" VALUES(92,'Quaerat quisquam voluptatem eius','Adipisci aliquam aliquam labore. Quaerat porro consectetur etincidunt dolor. Numquam quiquia neque sed magnam magnam quiquia ut. Porro etincidunt ipsum quiquia. Magnam est quisquam amet. Dolorem quisquam quisquam velit sed porro. Consectetur amet eius est quisquam. Labore quaerat numquam ipsum eius etincidunt. Voluptatem quiquia dolor aliquam quaerat amet est quisquam.','etincidunt','http://www.eius.com','Numquam','010222',34,31,3);
INSERT INTO "posts" VALUES(93,'Voluptatem porro quaerat numquam','Tempora amet quaerat ut voluptatem ut. Aliquam velit magnam voluptatem voluptatem. Modi quiquia eius etincidunt magnam dolorem adipisci. Ut etincidunt ut eius quaerat. Adipisci ut etincidunt sit adipisci quiquia ut dolor.','ipsum','http://www.velit.com','Porro','180419',35,21,14);
INSERT INTO "posts" VALUES(94,'Tempora tempora quaerat quisquam sit porro dolorem','Consectetur dolorem numquam numquam magnam consectetur. Ipsum sit ipsum modi velit eius. Ipsum consectetur eius dolor amet sed. Quisquam non etincidunt velit. Etincidunt dolorem labore non neque modi quisquam tempora. Aliquam quisquam sed neque sit voluptatem. Porro velit numquam ipsum amet quisquam labore sit. Neque amet velit numquam tempora consectetur voluptatem dolor.','tempora','http://www.ipsum.com','Est','130404',96,44,52);
INSERT INTO "posts" VALUES(95,'Ut dolore porro dolorem tempora numquam sit','Magnam etincidunt aliquam eius. Consectetur sit dolor modi. Sit velit tempora dolore sit aliquam sed. Velit sit modi velit. Non amet neque dolor. Dolore amet modi sed labore. Etincidunt consectetur tempora aliquam quiquia.','numquam','http://www.etincidunt.com','Etincidunt','040211',81,11,70);
INSERT INTO "posts" VALUES(96,'Ipsum tempora amet adipisci','Amet neque tempora eius numquam. Aliquam ipsum quisquam amet. Non dolorem ipsum non quiquia sed. Quisquam tempora modi porro. Tempora dolore ut etincidunt ipsum. Ipsum non amet etincidunt consectetur non. Amet ut etincidunt sit amet eius voluptatem sed. Labore eius non quaerat eius dolorem. Eius quiquia modi sit ut velit non. Eius eius velit numquam dolor.','sed','http://www.voluptatem.com','Labore','200430',95,28,67);
INSERT INTO "posts" VALUES(97,'Quiquia porro porro dolore dolor ipsum ut','Ut etincidunt quisquam voluptatem modi. Sed sed etincidunt aliquam quaerat quisquam eius quisquam. Labore dolore sed sit sed sed quiquia. Magnam neque tempora adipisci. Dolore porro voluptatem eius labore est sit quaerat. Labore tempora neque dolorem modi ut. Voluptatem est aliquam labore dolorem dolorem. Labore labore quiquia dolore est neque. Voluptatem voluptatem dolorem modi magnam.','sit','http://www.quiquia.com','Sit','091227',39,6,33);
INSERT INTO "posts" VALUES(98,'Quiquia ipsum ipsum dolorem dolor neque velit etincidunt','Consectetur porro numquam etincidunt. Magnam quisquam porro porro. Neque adipisci sed ut porro adipisci quiquia ut. Consectetur magnam amet quiquia dolorem. Quiquia numquam ut labore numquam eius. Tempora neque modi aliquam magnam magnam dolor tempora.','ipsum','http://www.est.com','Sed','120629',100,9,91);
INSERT INTO "posts" VALUES(99,'Ipsum aliquam dolorem velit neque ipsum non quiquia','Magnam ipsum numquam magnam est. Dolor etincidunt amet tempora. Etincidunt ut quisquam ipsum ipsum magnam. Eius ipsum non etincidunt dolore tempora quiquia quaerat. Ipsum dolore amet non quisquam neque amet ut. Est dolore adipisci aliquam porro. Velit dolorem velit consectetur dolore velit. Eius modi dolorem labore ut.','sed','http://www.ut.com','Dolor','000610',94,18,76);

DROP TABLE IF EXISTS vote_tracker;
CREATE TABLE vote_tracker (
		id INTEGER PRIMARY KEY,
		post_id INTEGER,
		vote_type VARCHAR,
		FOREIGN KEY(post_id) REFERENCES posts(id)
	);

INSERT INTO vote_tracker VALUES(0,42,'upvote');
INSERT INTO vote_tracker(post_id,vote_type) VALUES(17,'downvote');
COMMIT;